POST http://localhost:8080/odisee/document/generate
Accept: */*

< ../../../main/docker/var/request/test_1_HalloOdisee_single_odt.xml

###

POST http://localhost:8080/odisee/document/generate
Accept: */*

< ../var/request/test_2_HalloOdisee_single_pdf.xml

###

POST http://localhost:8080/odisee/document/generate
Accept: */*

< ../var/request/test_3_HalloOdisee_multiple_pdf.xml

###

POST http://localhost:8080/odisee/document/generate
Accept: */*

< ../../../main/docker/var/request/test_4_HalloOdisee_multiple_merge_pdf.xml

###

POST http://localhost:8080/odisee/document/generate
Accept: */*

< ../../../main/docker/var/request/test_5_HalloOdisee_single_imagebase64_pdf.xml

###

POST http://localhost:8080/odisee/document/generate
Accept: */*

< ../../../main/docker/var/request/test_7_ImageTest_pdf.xml

###
