== Odisee(R)

http://www.odisee.org/[www.odisee.org] +
Make Your Documents Smile.

=== Documentation

See file://src/main/asciidoc/Odisee.adoc[Odisee.adoc]

=== Building

Steps to setup environment

1. Optional: Configure HTTP proxy (see below)
2. Execute following build tasks:
+
[source,text]
----
./gradlew build
----

==== Proxy

.Docker
Put proxy settings into `/.env` file:

[source,text]
----
HTTP_PROXY=http://proxy.example.com:8888
HTTPS_PROXY=http://proxy.example.com:8888
NON_PROXY=localhost,example.com
----

.Gradle
Put proxy settings into Gradle's global configuration `$HOME/.gradle/gradle.properties`:

[source,text]
----
systemProp.http.proxyHost=proxy.example.com
systemProp.http.proxyPort=8888
systemProp.http.nonProxyHosts=localhost|127.0.0.1|example.com
systemProp.https.proxyHost=proxy.example.com
systemProp.https.proxyPort=8888
systemProp.https.nonProxyHosts=localhost|127.0.0.1|example.com
----

=== Copyright

Copyright (C) 2011-2019 art of coding UG (haftungsbeschränkt). +
Copyright (C) 2005-2010 Informationssysteme Ralf Bensmann.

Nutzung unterliegt Lizenzbedingungen. Use is subject to license terms.

=== License

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=== Registered Trademark

http://register.dpma.de/DPMAregister/marke/register/3020110473765/DE[Deutsches Patent- und Markenamt, Nr. 30 2011 047 376.]
