== Odisee(R)

http://www.odisee.org/[www.odisee.org] +
Make Your Documents Smile.

=== Documentation

See documentation/src/docs/asciidoc/Odisee.adoc[Odisee.adoc].

`POST /document/generate` accepts XML (`text/xml`, the default) and JSON (`application/json`).
The JSON shape is `webservice/src/main/resources/json/request.schema.json`.

=== Building

JDK 21, Gradle 8.14.5, and Grails 7.2.4. LibreOffice UNO is `org.libreoffice:libreoffice` 26.2.2 from Maven Central.

.Steps

1. Optional: Configure HTTP proxy (see below)
2. Point `JAVA_HOME` at a JDK 21
3. Execute following build tasks:
+
[source,text]
----
export JAVA_HOME=/path/to/jdk-21
./gradlew build
----

`build` compiles every module, runs the unit tests, and writes `build/distributions/odisee-2.6-linux-x86_64.zip`.

The zip contains `application.jar`, `bin/odictl`, `etc/`, the Java client, the LibreOffice extension, and the HTML documentation.

`:webservice:buildOdiseeImage` and `:webservice:libreOfficeTest` are not part of `build`. They need a local Docker daemon. The service image is Ubuntu 26.04 with OpenJDK 21 and headless LibreOffice Writer. The test image is `webservice/src/test/docker/libreoffice`.

GitHub Actions runs the same `./gradlew build` and uploads the zip. A git tag `v*` also publishes that zip as a GitHub Release.

==== Proxy

.Docker
Put proxy settings into `/.env` file:

[source,text]
----
HTTP_PROXY=http://proxy.example.com:8888
HTTPS_PROXY=http://proxy.example.com:8888
NON_PROXY=localhost,example.com
----

.Gradle
Put proxy settings into Gradle's global configuration `$HOME/.gradle/gradle.properties`:

[source,text]
----
systemProp.http.proxyHost=proxy.example.com
systemProp.http.proxyPort=8888
systemProp.http.nonProxyHosts=localhost|127.0.0.1|example.com
systemProp.https.proxyHost=proxy.example.com
systemProp.https.proxyPort=8888
systemProp.https.nonProxyHosts=localhost|127.0.0.1|example.com
----

=== Copyright

Copyright (C) 2011-2019 art of coding UG (haftungsbeschränkt). +
Copyright (C) 2005-2010 Informationssysteme Ralf Bensmann.

Nutzung unterliegt Lizenzbedingungen. Use is subject to license terms.

=== License

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=== Registered Trademark

http://register.dpma.de/DPMAregister/marke/register/3020110473765/DE[Deutsches Patent- und Markenamt, Nr. 30 2011 047 376.]
