= Odisee(R)

http://www.odisee.de/[www.odisee.de] +
Make Your Documents Smile.

== Documentation

See xref:src/main/asciidoc/Odisee.adoc[Odisee.adoc]

== Copyright

Copyright (C) 2011-2019 art of coding UG (haftungsbeschränkt).
Copyright (C) 2005-2010 Informationssysteme Ralf Bensmann.

Nutzung unterliegt Lizenzbedingungen. Use is subject to license terms.

== License

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

== Registered Trademark

http://register.dpma.de/DPMAregister/marke/register/3020110473765/DE[Deutsches Patent- und Markenamt, Nr. 30 2011 047 376.]
