plugins {
    id 'java'
    id 'com.github.bjornvester.xjc' version '1.9.1'
}

group = rootProject.group
version = rootProject.version

repositories {
    mavenCentral()
}

dependencies {
    implementation 'jakarta.xml.bind:jakarta.xml.bind-api:4.0.4'
    implementation 'jakarta.activation:jakarta.activation-api:2.1.4'
    implementation 'org.glassfish.jaxb:jaxb-runtime:4.0.6'
    implementation 'org.slf4j:slf4j-api:2.0.17'
    testImplementation 'junit:junit:4.13.2'
    testRuntimeOnly 'org.slf4j:slf4j-simple:2.0.17'
}

xjc {
    xsdDir.set(layout.projectDirectory.dir('src/main/schema'))
}
