== Users Guide

=== Clients

There's a http://www.odisee.de/odisee/product/odisee-client.xhtml[Windows client]
to test sending requests to Odisee. On the same page there are links to
Odisee client libraries (http://git.odisee.de/client-java/src[Java],
http://git.odisee.de/client-vbnet/src[VB.NET],
http://git.odisee.de/client-php/src[PHP]) along with examples how to use
the API.

==== Java

.Working with a single request
    :::java
    // Create Odisee client with service URL and authentication
    OdiseeClient odisee = OdiseeClient.createClient("http://service.odisee.de", "username", "password");
    // Create a new request for template HalloOdisee
    // By default, the last call to createRequest is remembered by the client
    odisee.createRequest("HalloOdisee");
    // Set value for userfield "hallo"
    odisee.setUserfield("hallo", "Odisee");
    // Set value in table "Tabelle1" cell "A4"
    odisee.setTableCellValue("Tabelle1", "A4", "value in a table cell");
    // Generate document, PDF by default
    byte[] document = odisee.process();

.Working with multiple requests
    :::java
    // Create Odisee client with service URL and authentication
    OdiseeClient odisee = OdiseeClient.createClient("http://service.odisee.de", "username", "password");
    // First request
    // Create a new request for template HalloOdisee
    Request odiseeRequest = odisee.createRequest("HalloOdisee");
    // Set value for userfield 'hallo'
    odisee.setUserfield(request, "hallo", "Odisee");
    // Set value in table "Tabelle1" cell "A4"
    odisee.setTableCellValue(request, "Tabelle1", "A4", "value in a table cell");
    // Second request
    // Create a new request for template HalloOdisee
    Request odiseeRequest = odisee.createRequest("HalloOdisee");
    // Set value for userfield 'hallo'
    odisee.setUserfield(request, "hallo", "Odisee, again");
    // Set value in table "Tabelle1" cell "A4"
    odisee.setTableCellValue(request, "Tabelle1", "A4", "Another value in a table cell");
    // Generate document, PDF by default
    byte[] document = odisee.process();

. Using the fluent API
    :::java
    // Create Odisee client with service URL and authentication
    OdiseeClient odisee = OdiseeClient.createClient("http://service.odisee.de", "username", "password");
    // Create a new request for template HalloOdisee
    // By default, the last call to createRequest is remembered by the client
    odisee.createRequest("HalloOdisee");
    byte[] document = client.setUserfield("Customer", "Acme Inc.").
                             setUserfield("Salutation", "Mr.").
                             setUserfield("Firstname", "John").
                             setUserfield("Lasstname", "Doe").
                             setUserfield("Street", "5678 Miller Ave").
                             setUserfield("Zipcode", "12345").
                             setUserfield("City", "Berlin").
                             setUserfield("Subject", "This is a letter").
                             process();

=== Testing

There are several Odisee clients available, for several programming languages.

.Visual Basic .NET
Download of ClickOnce installer is [here](http://files.odisee.de/product/odisee-client/windows/vbnet/).
The source code is publicly available: https://bitbucket.org/odisee/client-vbnet

.odipost
Post a request, catching the output in `HalloOdisee.odt`:

    $ odipost -f HalloOdisee_single_odt.xml -o HalloOdisee.odt

Result:

[source,text,linenum]
----
* About to connect() to 127.0.0.1 port 8080 (#0)
*   Trying 127.0.0.1...
* connected
* Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)
* Server auth using Basic with user 'odisee'
> POST /odisee/document/generate/1 HTTP/1.1
> Authorization: Basic b2Rpc2VlOm9kaXNlZQ==
> User-Agent: curl/7.27.0
> Host: 127.0.0.1:8080
> Accept: */*
> Content-Type: text/xml
> Content-Length: 456
>
} [data not shown]
* upload completely sent off: 456 out of 456 bytes
Oct 17 15:42:40 Ralfs-iMac.local soffice[90080] <Error>: clip: empty path.
< HTTP/1.1 200 OK
< Server: Apache-Coyote/1.1
< Cache-Control: no-cache,no-store,must-revalidate,max-age=0
< Content-disposition: inline; filename=HalloOdisee.odt
< Content-Type: application/vnd.oasis.opendocument.text
< Content-Length: 92665
< Date: Wed, 17 Oct 2012 13:42:41 GMT
<
{ [data not shown]
* Connection #0 to host 127.0.0.1 left intact
* Closing connection #0
----

The generated OpenDocument file:

[source,bash,linenum]
----
$ ls -l
total 216
-rw-r--r--  1 rbe  staff  92665 17 Okt 15:42 HalloOdisee.odt
----
